//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryML.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros_por_Autor
    {
        public long id { get; set; }
        public long autorID { get; set; }
        public long libroID { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
