//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryML.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DesafioMLEntities : DbContext
    {
        public DesafioMLEntities()
            : base("name=DesafioMLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autores> Autores { get; set; }
        public virtual DbSet<Editoriales> Editoriales { get; set; }
        public virtual DbSet<EventLog> EventLog { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<Libros_por_Autor> Libros_por_Autor { get; set; }
        public virtual DbSet<V_autores_libros> V_autores_libros { get; set; }
        public virtual DbSet<V_listaLibros> V_listaLibros { get; set; }
    
        public virtual int SP_Autores_INUP(Nullable<long> id, string nombre, string fecreg)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var fecregParameter = fecreg != null ?
                new ObjectParameter("fecreg", fecreg) :
                new ObjectParameter("fecreg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Autores_INUP", idParameter, nombreParameter, fecregParameter);
        }
    
        public virtual int SP_Editoriales_INUP(Nullable<long> id, string nombre, string ciudad, string fecreg)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var fecregParameter = fecreg != null ?
                new ObjectParameter("fecreg", fecreg) :
                new ObjectParameter("fecreg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Editoriales_INUP", idParameter, nombreParameter, ciudadParameter, fecregParameter);
        }
    
        public virtual int SP_EventLog_IN(string proceso, string descripcion, string fecha)
        {
            var procesoParameter = proceso != null ?
                new ObjectParameter("proceso", proceso) :
                new ObjectParameter("proceso", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EventLog_IN", procesoParameter, descripcionParameter, fechaParameter);
        }
    
        public virtual int SP_Libros_INUP(Nullable<long> id, string titulo, string sinopsis, Nullable<int> añopub, Nullable<long> editorialID, string fecreg)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var sinopsisParameter = sinopsis != null ?
                new ObjectParameter("sinopsis", sinopsis) :
                new ObjectParameter("sinopsis", typeof(string));
    
            var añopubParameter = añopub.HasValue ?
                new ObjectParameter("añopub", añopub) :
                new ObjectParameter("añopub", typeof(int));
    
            var editorialIDParameter = editorialID.HasValue ?
                new ObjectParameter("editorialID", editorialID) :
                new ObjectParameter("editorialID", typeof(long));
    
            var fecregParameter = fecreg != null ?
                new ObjectParameter("fecreg", fecreg) :
                new ObjectParameter("fecreg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Libros_INUP", idParameter, tituloParameter, sinopsisParameter, añopubParameter, editorialIDParameter, fecregParameter);
        }
    
        public virtual int SP_LibrosxAutor_INDEL(Nullable<long> id, Nullable<long> autorID, Nullable<long> libroID, string fecreg)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var autorIDParameter = autorID.HasValue ?
                new ObjectParameter("AutorID", autorID) :
                new ObjectParameter("AutorID", typeof(long));
    
            var libroIDParameter = libroID.HasValue ?
                new ObjectParameter("LibroID", libroID) :
                new ObjectParameter("LibroID", typeof(long));
    
            var fecregParameter = fecreg != null ?
                new ObjectParameter("fecreg", fecreg) :
                new ObjectParameter("fecreg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LibrosxAutor_INDEL", idParameter, autorIDParameter, libroIDParameter, fecregParameter);
        }
    }
}
