//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryML.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.Libros_por_Autor = new HashSet<Libros_por_Autor>();
        }
    
        public long id { get; set; }
        public long editorialID { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public int publicacion { get; set; }
        public string fecreg { get; set; }
    
        public virtual Editoriales Editoriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libros_por_Autor> Libros_por_Autor { get; set; }
    }
}
