//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryML.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_autores_libros
    {
        public long id { get; set; }
        public string titulo { get; set; }
        public string Autor { get; set; }
        public long libroID { get; set; }
    }
}
